# Generated by Django 5.0.3 on 2025-06-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order',
            new_name='cart',
        ),
    ]
