# Generated by Django 5.2.4 on 2025-08-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orderstatus_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
