# Generated by Django 5.2.4 on 2025-09-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, db_column='City', max_length=200, null=True)),
                ('digital_address', models.CharField(blank=True, db_column='DigitalAddress', max_length=100, null=True)),
                ('street_name', models.CharField(blank=True, db_column='StreetName', max_length=200, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('is_default', models.BooleanField(blank=True, db_column='IsDefault', null=True)),
            ],
            options={
                'db_table': 'Address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='UpdatedBy', null=True)),
            ],
            options={
                'db_table': 'Cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField(db_column='Quantity', default=1)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='UpdatedBy', null=True)),
            ],
            options={
                'db_table': 'CartItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('country_code', models.CharField(db_column='CountryCode', max_length=5, unique=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='UpdatedBy', null=True)),
            ],
            options={
                'db_table': 'Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(db_column='TrackingNumber', max_length=50)),
                ('dispatch_date', models.DateTimeField(blank=True, db_column='DispatchDate', null=True)),
                ('delivery_date', models.DateTimeField(blank=True, db_column='DeliveryDate', null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='UpdatedBy', null=True)),
            ],
            options={
                'db_table': 'Delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=3, max_digits=18)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='UpdatedBy', null=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('region_code', models.CharField(blank=True, db_column='RegionCode', max_length=10, null=True, unique=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', null=True)),
            ],
            options={
                'db_table': 'Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('subject', models.CharField(blank=True, db_column='Subject', max_length=200, null=True)),
                ('message', models.TextField(blank=True, db_column='Message', null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', null=True)),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='UpdatedBy', null=True)),
            ],
            options={
                'db_table': 'SavedItem',
                'managed': False,
            },
        ),
    ]
